'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DiffMerge.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to # Path to the text file containing the URLs (one per line)
        '''$urlsFile = &quot;./urlz.txt&quot;
        '''
        '''$downloadFolder = &quot;.&quot;
        '''
        '''# Create the folder if it doesn&apos;t exist
        '''if (!(Test-Path -Path $downloadFolder)) {
        '''    New-Item -ItemType Directory -Path $downloadFolder
        '''}
        '''
        '''# Read URLs from the file
        '''$urls = Get-Content $urlsFile
        '''
        '''
        '''foreach ($url in $urls) {
        '''    try {
        '''        $filename = Split-Path -Path $url -Leaf
        '''        $destination = Join-Path -Path $downloadFolder -ChildPath $filename
        '''        Invoke-WebRequest -U [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _new() As String
            Get
                Return ResourceManager.GetString("new", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to # Path to the text file containing the URLs (one per line)
        '''$urlsFile = &quot;./urls.txt&quot;
        '''
        '''# Folder to save the downloaded files
        '''$downloadFolder = &quot;.&quot;
        '''
        '''# Create the folder if it doesn&apos;t exist
        '''if (!(Test-Path -Path $downloadFolder)) {
        '''    New-Item -ItemType Directory -Path $downloadFolder
        '''}
        '''
        '''# Read URLs from the file
        '''$urls = Get-Content $urlsFile
        '''
        '''foreach ($url in $urls) {
        '''    try {
        '''        $filename = Split-Path -Path $url -Leaf
        '''        $destination = Join-Path -Path $downloadFolder -ChildPath $f [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property old() As String
            Get
                Return ResourceManager.GetString("old", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
